name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ master ]
    
jobs:
  # cypress-run:
  #   runs-on: ubuntu-latest
    
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v2

  #     - name: Cypress run
  #       uses: cypress-io/github-action@v2
  #       with:
  #         build: yarn build
  #         start: yarn preview --port 3000

  #     - name: Upload artifacts on fail
  #       uses: actions/upload-artifact@v2
  #       if: failure()
  #       with:
  #         name: failing-e2e-screenshots
  #         path: cypress/screenshots/

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [17.4.0]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2

    # E2E tests
    - name: Cypress run ðŸ§ª
      uses: cypress-io/github-action@v2
      with:
        build: yarn build
        start: yarn preview --port 3000
    - name: Upload artifacts on fail ðŸ“·
      uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: failing-e2e-screenshots
        path: cypress/screenshots/

    # BUILD
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies ðŸ› 
      run: yarn --frozen-lockfile

    - name: Build App âš™ ðŸ¦º
      env:
        deploy_main: halabala
      run: yarn build
        
    # DEPLOY
    - name: Deploy ðŸš€
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: dist # The folder the action should deploy.
